#Students CRUD
###
GET {{baseUrl}}/api/students

###
GET {{baseUrl}}/api/students/2

###
POST {{baseUrl}}/api/students
Content-Type: application/json

{"name": "test3", "email": "testemail3@gmail.com"}

###
PUT {{baseUrl}}/api/students/1
Content-Type: application/json

{"name": "testPut", "email": "testPut@gmail.com"}

###
PATCH {{baseUrl}}/api/students/1
Content-Type: application/json

{"name": "testPatch"}

###
PATCH {{baseUrl}}/api/students/1
Content-Type: application/json

{"email": "testPatch@gmail.com"}

###
DELETE {{baseUrl}}/api/students/1



#Course CRUD
###
GET {{baseUrl}}/api/courses

###
GET {{baseUrl}}/api/courses/1

###
POST {{baseUrl}}/api/courses
Content-Type: application/json

{"course_name": "test4", "instructor": "testInstructor2", "credit_hours": 4}

###
PUT {{baseUrl}}/api/courses/1
Content-Type: application/json

{"course_name": "testPut", "instructor": "testInstructorPut", "credit_hours": 4}

###
PATCH {{baseUrl}}/api/courses/2
Content-Type: application/json

{"course_name": "test1"}

###
DELETE {{baseUrl}}/api/courses/1

#Enrollments
###
POST {{baseUrl}}/api/enrollments
Content-Type: application/json

{
  "student_id": 2,
  "course_id": 3,
  "assignment1": 85.5,
  "assignment2": 90,
  "midterm_exam": 78,
  "final_exam": 88,
  "final_project": 92
}

###
GET {{baseUrl}}/api/enrollments

###
GET {{baseUrl}}/api/enrollments?student_id=2&course_id=2

###
GET {{baseUrl}}/api/enrollments/2/3